"""Database utilities for storing autonomous repair sessions."""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Generator
import logging

from sqlalchemy import Boolean, DateTime, Integer, Text, create_engine
from sqlalchemy.engine import Engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, sessionmaker
from sqlalchemy.types import JSON


logger = logging.getLogger(__name__)


class Base(DeclarativeBase):
    """Base class for SQLAlchemy ORM models."""


class RepairSession(Base):
    """Persistent model for a single autonomous repair run."""

    __tablename__ = "repair_sessions"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    initial_code: Mapped[str] = mapped_column(Text, nullable=False)
    final_code: Mapped[str] = mapped_column(Text, nullable=False)
    is_fixed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    history: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    tokens_used: Mapped[int] = mapped_column(Integer, nullable=False, default=0)


DB_DIR = Path(__file__).resolve().parent / "data"
DB_DIR.mkdir(parents=True, exist_ok=True)
DB_PATH = DB_DIR / "repair_sessions.db"
DATABASE_URL = f"sqlite:///{DB_PATH.as_posix()}"

engine: Engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},
    future=True,
)
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False, future=True)


def init_db() -> None:
    """Create database tables if they do not already exist.

    Args:
        None.

    Returns:
        None.

    Raises:
        SQLAlchemyError: If table creation fails.
    """
    try:
        Base.metadata.create_all(bind=engine)
    except SQLAlchemyError:
        logger.exception("Failed to initialize database schema at %s", DB_PATH)
        raise


@contextmanager
def get_db_session() -> Generator[Session, None, None]:
    """Yield a managed SQLAlchemy session and close it afterward.

    Args:
        None.

    Yields:
        Active database session object.

    Raises:
        SQLAlchemyError: If session creation fails.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def save_session(
    initial_code: str,
    final_code: str,
    is_fixed: bool,
    history: list[str],
    tokens_used: int,
) -> RepairSession:
    """Persist a completed repair session.

    Args:
        initial_code: Source code before repair.
        final_code: Source code after repair.
        is_fixed: Whether repair resolved the issue.
        history: Ordered timeline/thought entries generated by the agent.
        tokens_used: Number of model tokens consumed during repair.

    Returns:
        The created RepairSession ORM object.

    Raises:
        SQLAlchemyError: If persisting the record fails.
    """
    session_row = RepairSession(
        initial_code=initial_code,
        final_code=final_code,
        is_fixed=is_fixed,
        history=history,
        tokens_used=tokens_used,
    )
    try:
        with get_db_session() as db:
            db.add(session_row)
            db.commit()
            db.refresh(session_row)
            return session_row
    except SQLAlchemyError:
        logger.exception(
            "Failed to save repair session (is_fixed=%s, tokens_used=%s)",
            is_fixed,
            tokens_used,
        )
        raise


def get_recent_sessions(limit: int = 20) -> list[dict[str, Any]]:
    """Fetch recent sessions ordered from newest to oldest.

    Args:
        limit: Maximum number of records to return.

    Returns:
        List of dictionaries suitable for UI/API responses.

    Raises:
        SQLAlchemyError: If querying the database fails.
    """
    safe_limit = max(1, limit)
    try:
        with get_db_session() as db:
            rows = (
                db.query(RepairSession)
                .order_by(RepairSession.timestamp.desc())
                .limit(safe_limit)
                .all()
            )
            return [
                {
                    "id": row.id,
                    "timestamp": row.timestamp.isoformat(),
                    "initial_code": row.initial_code,
                    "final_code": row.final_code,
                    "is_fixed": row.is_fixed,
                    "history": row.history,
                    "tokens_used": row.tokens_used,
                }
                for row in rows
            ]
    except SQLAlchemyError:
        logger.exception("Failed to fetch recent sessions (limit=%s)", limit)
        raise


init_db()
